name: "Sing-box Proxy"
version: "1.3.7"
slug: "singbox_proxy"
description: "HTTP/SOCKS proxy through configurable sing-box servers"
arch:
  - aarch64

startup: services
boot: auto
host_network: true
init: false

webui: "http://[HOST]:[PORT:9090]/ui/"
ingress: true
ingress_port: 9090
ingress_entry: "ui/"
panel_icon: "mdi:router-network"
panel_title: "Sing-box Proxy"
panel_admin: false

options:
  secret: "ChangeThisSecret_2026"
  http_proxy_port: 2081
  socks_proxy_port: 2080
  socks_auth_enabled: false
  http_auth_enabled: false
  proxy_username: "user"
  proxy_password: "password"
  urltest_interval: "2m"
  urltest_tolerance: 50
  log_level: "info"
  servers_json: "[]"

schema:
  secret: "str"
  http_proxy_port: "int(1,65535)"
  socks_proxy_port: "int(1,65535)"
  socks_auth_enabled: "bool"
  http_auth_enabled: "bool"
  proxy_username: "str"
  proxy_password: "password"
  urltest_interval: "str"
  urltest_tolerance: "int(0,1000)"
  log_level: "list(trace|debug|info|warn|error|fatal|panic)"
  servers_json: "str"

ports:
  2080/tcp: 2080
  2081/tcp: 2081
  9090/tcp: 9090

ports_description:
  2080/tcp: "SOCKS5 proxy"
  2081/tcp: "HTTP proxy"
  9090/tcp: "Internal dashboard / Clash API"
